-- MySQL Script generated by MySQL Workbench
-- Mon 07 Nov 2016 02:57:59 AM +03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema black_jack
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `black_jack` ;

-- -----------------------------------------------------
-- Schema black_jack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `black_jack` DEFAULT CHARACTER SET utf8 ;
USE `black_jack` ;

-- -----------------------------------------------------
-- Table `black_jack`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `black_jack`.`user` ;

CREATE TABLE IF NOT EXISTS `black_jack`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` CHAR(64) NOT NULL,
  `first_name` VARCHAR(127) NOT NULL,
  `middle_name` VARCHAR(127) NULL,
  `last_name` VARCHAR(127) NOT NULL,
  `display_name` VARCHAR(255) NOT NULL COMMENT 'Default FirstName + LastName',
  `rating` INT NOT NULL DEFAULT 0,
  `account_balance` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `bonus_points_balance` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `type` ENUM('admin', 'player') NOT NULL COMMENT 'user type - admin, player',
  `status` ENUM('offline', 'away', 'online') NOT NULL COMMENT 'user status - online, offline, away',
  `registred` DATETIME NULL COMMENT 'NULL means that email is not confirmed.',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `EMAIL` (`email` ASC),
  INDEX `STATUS` (`status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `black_jack`.`userstat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `black_jack`.`userstat` ;

CREATE TABLE IF NOT EXISTS `black_jack`.`userstat` (
  `user_id` INT UNSIGNED NOT NULL,
  `game_type` ENUM('computer', 'player') NOT NULL,
  `wins` INT NOT NULL DEFAULT 0,
  `losses` INT NOT NULL DEFAULT 0,
  `ties` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`, `game_type`),
  INDEX `fk_userstat_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_userstat_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `black_jack`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `black_jack`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `black_jack`.`chat` ;

CREATE TABLE IF NOT EXISTS `black_jack`.`chat` (
  `chat_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) BINARY NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`chat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `black_jack`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `black_jack`.`contact` ;

CREATE TABLE IF NOT EXISTS `black_jack`.`contact` (
  `user_id` INT UNSIGNED NOT NULL,
  `contact_id` INT UNSIGNED NOT NULL,
  INDEX `fk_contact_user2_idx` (`contact_id` ASC),
  INDEX `fk_contact_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`user_id`, `contact_id`),
  CONSTRAINT `fk_contact_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `black_jack`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_user2`
    FOREIGN KEY (`contact_id`)
    REFERENCES `black_jack`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `black_jack`.`chat_user_ref`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `black_jack`.`chat_user_ref` ;

CREATE TABLE IF NOT EXISTS `black_jack`.`chat_user_ref` (
  `chat_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  INDEX `fk_chat_user_ref_chat1_idx` (`chat_id` ASC),
  INDEX `fk_chat_user_ref_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`chat_id`, `user_id`),
  CONSTRAINT `fk_chat_user_ref_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `black_jack`.`chat` (`chat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_user_ref_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `black_jack`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `black_jack`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `black_jack`.`message` ;

CREATE TABLE IF NOT EXISTS `black_jack`.`message` (
  `message_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_from_id` INT UNSIGNED NOT NULL,
  `chat_id` BIGINT UNSIGNED NULL COMMENT 'NULL for private messsage',
  `user_to_id` INT UNSIGNED NULL COMMENT 'NULL for chat message',
  `text` VARCHAR(4096) NOT NULL,
  `time` DATETIME NOT NULL,
  INDEX `fk_message_chat1_idx` (`chat_id` ASC),
  INDEX `fk_message_user1_idx` (`user_from_id` ASC),
  PRIMARY KEY (`message_id`),
  INDEX `fk_message_user2_idx` (`user_to_id` ASC),
  CONSTRAINT `fk_message_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `black_jack`.`chat` (`chat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`user_from_id`)
    REFERENCES `black_jack`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user2`
    FOREIGN KEY (`user_to_id`)
    REFERENCES `black_jack`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `black_jack`.`account_operation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `black_jack`.`account_operation` ;

CREATE TABLE IF NOT EXISTS `black_jack`.`account_operation` (
  `account_operation_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `ammount` DECIMAL(12,2) NOT NULL,
  `type` ENUM('payment', 'withdrawal', 'win', 'loss', 'buy') NOT NULL,
  `time` DATETIME NOT NULL,
  `comment` VARCHAR(255) NULL,
  INDEX `fk_account_operation_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`account_operation_id`),
  CONSTRAINT `fk_account_operation_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `black_jack`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
